version: "3"
services:
  ethereal-umbraco-cms:
    image: mcr.microsoft.com/dotnet/sdk 
    links: 
      - ethereal-umbraco-db
    working_dir: "/app"
    ports: 
      - "59036:59036"
    volumes: 
      - "./cms:/app"
    command: "dotnet watch run"

  ethereal-umbraco-db:
    image: mcr.microsoft.com/mssql/server
    ports: 
      - "1433:1433"
    environment: 
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=SApassword123!"
      - "MSSQL_PID=Express"
    volumes: 
      - "/var/opt/mssql"
      - "./.docker/database/:/var/scripts/"